title: Jay Wang, D.Sc.
logo: "./images/JayWang200.png?raw=true" 
description: 
  <br/>
  Always curious. Forever exploring.
  <br/><br/>
  <a href="https://www.linkedin.com/in/jaywangusa/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
google_analytics: UA-159296632-1
