title: Dr. Chaojie (Jay) Wang
logo: "./images/logo.png?raw=true" 
description: 
  <br/>
  I am a seasoned software engineer with strong people and communication skills and  
  strong commitment to individual excellence and team success. I am always curious and am a lifelong learner.
  <br/>
  <a href="https://www.linkedin.com/in/jaywangusa/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
