title: Dr. Chaojie (Jay) Wang
logo: "./images/logo.png?raw=true" 
description: 
  <br/>
  A seasoned software engineer with strong communication skills and  
  commitment to individual excellence and team success. Always curious and forever exploring.
  <br/>
  “路漫漫其修远兮，吾将上下而求索。” - 屈原
  <br/>
  <a href="https://www.linkedin.com/in/jaywangusa/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
