title: DR. JAY WANG
logo: "./images/logo.png?raw=true" 
description: 
  <br/>
  <b><i>Always Curious; Forever Exploring.</i></b>
  <br/><br/>
  <b>路漫漫其修远兮，吾将上下而求索。 </b>
  <br/><br/>
  <a href="https://www.linkedin.com/in/jaywangusa/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
