title: Dr. Chaojie (Jay) Wang
logo: "./images/logo.png?raw=true" 
description: 
  <br/>
  Always curious and forever exploring.
  <br/><br/>
  “路漫漫其修远兮，吾将上下而求索。” 
  <br/><br/>
  <a href="https://www.linkedin.com/in/jaywangusa/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
