title: Dr. Chaojie (Jay) Wang
logo: "./images/logo.png?raw=true" 
description: 
I am a seasoned software and systems engineer, data scientist, project manager, and researcher with experience in System Design,
Data Analytics, Health IT and Informatics, and IT Modernization; I have Strong people and communication skills and  
strong commitment to individual excellence and team success. I am always curious and a lifetime learner.
  <br/>
  <a href="https://www.linkedin.com/in/jaywangusa/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
