title: Dr. Jay Wang
logo: "./images/logo.png?raw=true" 
description: 
  <br/>
  <a href="https://github.com/wcj365/wcj365.github.io/blob/master/publications.md">Publications</a>   
  <br/>
  <b>Always curious; forever exploring.</b>
  <br/><br/>
  <b>“路漫漫其修远兮，吾将上下而求索。” </b>
  <br/><br/>
  <a href="https://www.linkedin.com/in/jaywangusa/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
